on:
  push:
    branches:
      - master

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

        with:
          node-version: "20"

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.crunchyapps.com
          username: ftpCicd@crunchyapps.com
          password: K@8u%C6RiIJ5
          server-dir: /public/fbfx/
